# Generated by Django 4.2.11 on 2025-01-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPLLeagueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLUB_NAME', models.CharField(max_length=250)),
                ('CLUB_LOGO', models.CharField(max_length=250)),
                ('TOTAL_NUMBER_OF_GAMES_PLAYED', models.CharField(max_length=250)),
                ('TOTAL_NUMBER_OF_WINS', models.CharField(max_length=250)),
                ('TOTAL_NUMBER_OF_LOSSES', models.CharField(max_length=250)),
                ('GOALS_FOR', models.CharField(max_length=250)),
                ('GOALS_AGAINST', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EPLTopScorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLAYER_NAME', models.CharField(max_length=250)),
                ('CLUB_NAME', models.CharField(max_length=250)),
                ('CLUB_LOGO', models.CharField(max_length=250)),
                ('TOTAL_NUMBER_GOALS', models.CharField(max_length=250)),
            ],
        ),
    ]
