name: Deploy global-tools

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: image build
    
      run: |
        
        ./scripts/dockerbuild.sh 

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build and push
      uses: docker/build-push-action@v2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-1
      with:
        push: false
        tags: nosaugowe/epl:latest
        shell: bash
        run: |
           docker run -d --name epltable nosaugowe/epl:latest
           docker cp $(cat /etc/hostname):/opt/epl/EPLTable.png /tmp
           aws s3 cp /tmp/EPLTable.png s3://epltable/EPLTable.png

 