name: Deploy global-tools

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: image build
       
      run: |
        echo "Running Docker build......."
        docker build -t nosaugowe/epltable .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nosaugowe/epltable:latest

    - name: Container run
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        docker pull nosaugowe/epltable:latest
        CONTAINERID=$(sudo docker ps -a | awk '{ print $1, $2 }' | grep epltable | awk '{print $1 }')
        docker commit CONTAINERID nosaugowe/epltable2
        docker cp $(docker run -d --name epltable3 nosaugowe/epltable2:latest):/opt/epl/EPLTable.png /tmp
        #docker run -d --name epltable nosaugowe/epltable:latest
        #docker start $(docker ps -a | awk '{ print $1, $2 }' | grep  nosaugowe/epltable:latest | awk '{print $1 }')
        #docker cp $(docker ps -a | awk '{ print $1, $2 }' | grep  nosaugowe/epltable:latest | awk '{print $1 }'):/opt/epl/EPLTable.png /tmp
        #docker cp $(docker run -d --name epltable nosaugowe/epltable:latest):/opt/epl/EPLTable.png /tmp

        
        
        




    
      
       
    
   