name: Deploy EnglishPremierLeagueTable

on:
  push:
    branches: [ main ]
  schedule:
  - cron: '0 18 * * 0-6'

  repository_dispatch:
    types: [EPLApiCall]
  


jobs:
  EPLTable_Deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout repo && run script
      run: |
         echo "payload=${{ github.event.client_payload }}" >> $GITHUB_ENV
         #echo "Printing the payload value..."
         cat $GITHUB_ENV
         
         
      shell: bash

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: nosaugowe/epltable:latest

    #- name: Container run & s3 Bucket push
      #env:
        #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        #AWS_DEFAULT_REGION: us-east-1
        #S3_BUCKET: epltable
        #EPL_PNG_FILE: EPLTable.png 
      #run: |
        #echo "Pulling Docker Image................."
        #docker pull nosaugowe/epltable:latest
        #echo "Running the Docker Container........."
        #docker run --rm --name epltable -e EPL_PNG_FILE="${EPL_PNG_FILE}" -e S3_BUCKET="${S3_BUCKET}" -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" -e AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}" nosaugowe/epltable:latest
        
   
        
        




    
      
       
    
   
