name: Deploy global-tools

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: image build
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-west-2
    
      run: |
        echo "Running Docker build......."
        docker build -t nosaugowe/epltable .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nosaugowe/epltable:latest

    - name: Container run and build
      uses: addnab/docker-run-action@v3
      with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      registry: docker.io
      image: nosaugowe/epltable:latest
      run: echo "hello world"

    
      
       
    
   