name: Deploy global-tools

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: image build
       
      run: |
        echo "Running Docker build......."
        docker build -t nosaugowe/epltable .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nosaugowe/epltable:latest

    - name: Container run
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-1
        S3_BUCKET: epltable
        EPL_PNG_FILE: EPLTable.png 
      run: |
        echo "Pulling Docker Image................."
        docker pull nosaugowe/epltable:latest
        echo "Running the Docker Container........."
        docker run --rm --name epltable -e EPL_PNG_FILE="${EPL_PNG_FILE}" -e S3_BUCKET="${S3_BUCKET}" -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" -e AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}" nosaugowe/epltable:latest
        
        
        
        




    
      
       
    
   